### ISSUE TITLE
Players cannot properly refresh missions in 2023

### ISSUE THREAD

**Issue by Sapherises** [Ordwen/ODailyQuests#9]
version: 1.3.6
server: 1.19.2 paper
My server setting is to refresh tasks for all players at midnight every day，This works fine in 2022, but starting from January 1, 2023, there will be a problem with the task refresh time of all players. It will show that the remaining refresh time is negative, and the task cannot be refreshed normally.
I've tried deleting config files and resetting all player progress, but it still doesn't work.

**Comment by Ordwen** [comment]
Hi,
You are right, this bug is related to the new year.

You will find a plugin fix just below. This one, when the player connects, checks if he is present in a list and if he is not, resets his quests with the command and adds him in the list (in a config.yml file). Just put the plugin that is inside the .zip on your server, and after restarting, all players connecting should have their quests reset at least once. 

I couldn't do it any other way for this version because I didn't handle the version changes properly. Sorry for those who have already reset quests manually, and I promise to learn from my mistakes.

To simplify support and take advantage of the snapshots that bring a lot of fixes, I suggest you join the Discord server and upgrade to version 2.0, available in an associated channel called #snapshots. Details on how to make the transition successfully are also given here. If you upgrade to version 2.0, you can remove this patch.

The strange thing is that you say you have reset the progressions. Did you delete the file, turn off the server? If so, it should have worked...

Sorry for the inconvenience, and if you have any problem, don't hesitate.
Sincerely

[ODailyQuestsNewYearFix-1.0.zip](https://github.com/Ordwen/ODailyQuests/files/10331338/ODailyQuestsNewYearFix-1.0.zip)
